### ISSUE TITLE
How to reset or clear text in input?

### ISSUE THREAD

**Issue by gorbyoz** [SkrewEverything/react-native-input-prompt#5]
I need a method to clear the text from the input in the prompt. 

E.g. Prompt appears, user types something and clicks "add another one" so the prompt should stay visible and clear the user input.

**Comment by SkrewEverything** [comment]
Nice feature to add. But currently I'm busy in other projects though.

If you want, I can guide you to implement it yourself and you can share it by submitting a pull request.

If you are not comfortable with reading and editing other peoples code(happens mostly for beginners), then I can add that feature but it will take some time.

But if you are in a hurry and can't wait, I can give you some tips about adding your feature.

Mail me if you want any assistance so that I can get back to you much faster than in GitHub.

**Comment by gorbyoz** [comment]
That would be awesome.

I'm always up to learning.

Kind regards,
Oz



-------- Original message --------

**Comment by gorbyoz** [comment]
I did find a way already. Just passing {this.state.value} to the TextInput

<TextInput
placeholder={this.props.placeholder}
style={styles.textInput}
onChangeText={this._onChangeText.bind(this)}
onSubmitEditing={this._onSubmit.bind(this)}
autoFocus={true}
**value={this.state.value}**
/>

Thank you very much!!!

**Comment by SkrewEverything** [comment]
@gorbyoz I'm glad you have found a way by yourself.
